added ts & refactor form folder
Frolikss/cashback pull request #2
Opened 2023-02-16 09:38 UTC by Frolikss

2023-02-16 09:53 UTC, LysiukOleksandr requested changes

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/Button.tsx
> +  variant?: string;
не стринг. Тут надо создать енамку из возможных вариантов...потом создать объект... (ключ - значение из енамки  / значение - класс который буш юзать)... ну и соответственно в эту енамку как тип сюда добавь

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/Button.tsx
> +  children: React.ReactNode;
та просто RejObject<HTML....> ReactNode
удали импорт реакта, и деструктуризируй сразу

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/Button.tsx
> +export const Button: FC<Props> = ({ variant, modalRef, children, ...props }) => {
и кста, можешь по дефолту какой-нить вариант задать, если нужно конеш...

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/FillForm.tsx
> +import { Field } from '@constants';
а че оно в самом верху?

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/FillForm.tsx
> +          <React.Fragment key={index}>
простоо фрагмент, нахуй те этот импорт реакта

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/Input.tsx
> +  variant: string;
Тож самое что и выше

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/Select.tsx
> +  options: number[];
а шо, ток цифры могут быть?))

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/Select.tsx
>    const optionsDivStyle = `block px-2 absolute text-xl flex flex-col gap-2 w-2/3 rounded-lg rounded-b-none left-0 bottom-full bg-accent-light after:content-[''] after:absolute after:bg-contain after:
выше подними, за тело компонента

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/components/form/Select.tsx
> +            if (option === initialValue) return null;
как варик можно просто фильтрм после сорта сделать...но так тож можно(это на будущее написал)...

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/constants/interfaces.ts
> +  validation: {
Это лишнее, либа предоставляет все типы которые тебе надо, заюзай оттуда)

2023-02-16 09:53 UTC, LysiukOleksandr commented on src/constants/interfaces.ts
> +  variant: string;
не стрингааааа)))0)

2023-02-16 09:57 UTC, Frolikss commented on src/components/form/Select.tsx
>    const optionsDivStyle = `block px-2 absolute text-xl flex flex-col gap-2 w-2/3 rounded-lg rounded-b-none left-0 bottom-full bg-accent-light after:content-[''] after:absolute after:bg-contain after:
v uppercase suka

2023-02-17 09:57 UTC, LysiukOleksandr requested changes

2023-02-17 09:57 UTC, LysiukOleksandr commented on custom.d.ts
> +declare module '*.png' {
??

2023-02-17 09:57 UTC, LysiukOleksandr commented on package.json
> +    "@types/react-dom": "^18.0.10",
а теперь открываешь этот файл...смотришь что нужно перенести в дев зависимости...и переносишь

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/components/form/Input.tsx
> +  ref: ForwardedRef<unknown>;
unknown))

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/components/form/Select.tsx
> +      {initialValue.value}
a gde a sho?

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/constants/componentsContent.js
> +export const SHOW_MAX_CELLS = [
kakie cells syka, kakie dlya chego? ebat naming ya ebal

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/constants/componentsVariants.ts
> +  [ButtonVariants.DEFAULT]: ''
zachem? prosto bez varianta esli nado default...

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/constants/componentsVariants.ts
> +    'flex-1 text-accent-primary rounded-lg border-3 border-accent-primary hover:border-accent-dark',
общие стили вынеси в сам компонент в класс

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/constants/enums.ts
> +}
export enum ButtonVariants {
PRIMARY = 'primary',
SECONDARY = 'secondary'....
}

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/constants/enums.ts
> +export enum InputVariants {
the same as above

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/constants/fields/loginFieldsData.js
>  export const LOGIN_FIELDS_DATA = [
ykazhi tip, shob srazy videt sho ne tak

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/constants/componentsVariants.ts
> +  [InputVariants.LOGIN]:
kakoi nahui variant login, sho blyat? если совпадёт нахуй на разных страницах, то че за хуйня?? СУКА БЛЯТЬ

2023-02-17 09:57 UTC, LysiukOleksandr commented on src/pages/LoginPage.jsx
> +import React from 'react';
ne nado eto yzhe esli sho, s 2022 goda...no pohui, eto ne oshibka

2023-02-17 13:50 UTC, merged